# onec run server, can not change
# secret_key = "mahjong_is_fun"

# only postgres
db_url = "postgres://spoon:mahjong_at_home@nest:5432/mahjong_at_home"

# Super admin username
# super_username = "admin@math.com"

# Super admin password
# super_password = "mahjong_is_fun"

# token expiration time after login
token_exp_after = 1
