[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = ["fullstack"] }
jsonwebtoken = { version = "10.2.0", features = ["rust_crypto"], optional = true }
password-auth = { version = "1.0.0", optional = true }
sea-orm = { version = "2.0.0-rc", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros", "with-json", "with-chrono"], optional = true }
serde = { version = "1.0.228", features = ["serde_derive"]}
tokio = { version = "1.48.0", optional = true }
toml = { version = "0.9.10", optional = true }
migration = { path="../migration", optional = true }
uuid = { version = "1.19.0", features = ["serde","v4"], optional = true }

[features]
# default = ["server"]
server = ["dioxus/server","dep:tokio","dep:jsonwebtoken","dep:migration","dep:password-auth","dep:uuid","dep:sea-orm","dep:toml"]
